name: Tests CI

on:
  - push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: install deps
        shell: bash
        run: choco install --allow-empty-checksums -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo

      - name: install more deps
        shell: bash
        run: bash.exe win-install.sh

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: install
        run: yarn install --frozen-lockfile

      - name: rebuild
        run: yarn run start
