name: Tests CI

on:
  - push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Install node-gyp
        run: npm install -g node-gyp

      - name: Install deps
        run: msys2do . .github/workflows/win-install.sh

      - name: Checkout
        uses: actions/checkout@v3

      - name: install
        run: yarn install --frozen-lockfile

      - name: rebuild
        run: yarn run build
